# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 大道至简，触类旁通
email: xulei.home@163.com
description: > # this means to ignore newlines until "baseurl:"
  This is my home page. Though my knowledge is shallow, I will keep on working hard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
weibo_username: Manyghosts Xu
github_username:  Redchar1992

# Build settings
markdown: kramdown
